### ISSUE TITLE
trivial bug in packages/moode-player/build.sh

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/pkgbuild#10]
Looking through the output of `apt-cache show moode-player` on a running 8.3.2 instance, I noticed the homepage reference is incorrect for all versions of the moode-player package. Here's just the first
```
pi@moode:~ $ apt-cache show moode-player
Package: moode-player
Version: 8.3.2-1moode1
...
Homepage: https://www.moode.org
Description: moOde audio player
...
```
A quick grep on the contents of this repo suggests the issue arises in the `--url` line of `packages/moode-player/build.sh`. Here it is in context

 ```
fpm -s dir -t deb -n $PKGNAME -v $PKGVERSION \
--license GPLv3 \
--category sound \
-S moode \
--iteration $DEBVER$DEBLOC \
-a all \
--deb-priority optional \
--url https://www.moode.org \
```

**Comment by moodeaudio** [comment]
Fixed https://github.com/moode-player/pkgbuild/commit/9e22be60dd7d854ebe71000acb9bb587f8737605
