### ISSUE TITLE
Trying to compile from scratch

### ISSUE THREAD

**Issue by psych0d0g** [moode-player/pkgbuild#7]
im trying to get moode to compile from scratch on a vanilla debian bullseye,
getting up to some npm things and then it fails with:
```
[17:42:03] Finished 'deploy' after 750 ms
SQL database location is '/pkgbuild/packages/moode-player/build/moode-sqlite3.db'
Station logos location is '/root/moode.dev/moode/var/local/www/imagesw/radio-logos'
Export station data
Export station logos
Error: radio station base backup ../dist/binary/moode-stations-full_8.0.0.zip not found!
The command '/bin/sh -c /bin/bash && . pkgbuild/scripts/setenv.sh.example &&     /bin/bash && cd pkgbuild/packages/moode-player &&     ./build.sh' returned a non-zero code: 1
```

i wasnt able to find any reference in the docs repo to moode-stations-full_8.0.0.zip, is there something missing? where do i get that zip file from?

**Comment by moodeaudio** [comment]
The dev docs have not been updated in a while and the TODO list item to do so is not getting much priority these days. I'll make an effort.

The commands below should get you going.
```bash
# Seed the radio station base zip before initial moode-player package build
cd ~/pkgbuild/packages/moode-player
mkdir dist
mkdir dist/binary
cd dist/binary
wget --no-verbose https://dl.cloudsmith.io/public/moodeaudio/m8y/raw/files/moode-stations-full_8.0.0.zip
cd ../..
```

**Comment by psych0d0g** [comment]
hmm, i see, for now i removed the corresponding lines that create "update patch" zip files from the build.sh as another workaround, since i dont really know the mechanics behind the patching system for the radio stations, would it be feasible to incorporate the wget command into the normal build.sh to download the last full major version zip if one is building outside of a moode environment?

something like this:
https://github.com/moode-player/pkgbuild/pull/8/files#diff-b3447a5bfa46fba18edc0b57a634f2bdc25ed4d96c4c37a454b9e33446f415f9R118

**Comment by moodeaudio** [comment]
Closed due to being stale
