### ISSUE TITLE
Make build scripts more flexible to enable Compiling for non-arm architectures

### ISSUE THREAD

**Issue by psych0d0g** [moode-player/pkgbuild#9]
I am kinda motivated to get this whole thing working within the context of a dedicated docker container that can be spun up on x86_64 hardware, maybe as a trimmed down set of packages (kernel modules and that kinda stuff are pointless within docker)
might need some documentation aswell (underlying host requirements and such) but should be possible.
i would invest time into archiving that goal myself.

my question now would be, does it make sense to get backwards and arm compatible changes merged here, or should i create and maintain a full hardfork for that work?

(the refactoring of the build scripts kinda plays into this goal aswell tbh)

**Comment by bitkeeper** [comment]
I don't think the basic port to x86_64 of the packages it self is that hard, at least when the target distro is also debian based.
Most of the packages will already build without problems under different architectures.

I have update the readme of this repo including an graphical overview of the packages and inter dependencies.

**Comment by psych0d0g** [comment]
nice, the graphical overview is really helpful, thanks for that :)

**Comment by bitkeeper** [comment]
By-the-way the moOde code (not package build script) is a different beast. That contains a lot of functionality/code only suitable for the Pi.

**Comment by psych0d0g** [comment]
yup, i thought so, will come to that when i have a docker container build that is actually "trying" to serve the "website" from the moOde repo itself :)
i am curious about what i got myself into already :joy:

**Comment by bitkeeper** [comment]
Haha I recognize that feeling from when I did the introduction of the package builing in combination with the Bullseye port at the same time ;-)

**Comment by psych0d0g** [comment]
yeah, well, i aim for a basically working starting image.
the background is, i have an NGO, (open fablab / makerspace) and we have a little thinclient running as an in-lab server using kubernetes, providing us with authorization to the door, several machines etc, and it has a headphone plug, and an amp with speakers right next to it. 
currently we play music using a laptop sitting besides it, and that is just not clean XD
so my idea is to get a basic moOde docker container working, throw that at the kubernetes instance, and let people play music in the lab using their phones browsers etc :)
a dedicated raspberry pi for that purpose only is just too expensive since a while, or not possible to get ahold of alltogether^^

and why moOde?
i had it running on my kitchen speaker setup on a PI for quite some time, and compared to mopidy or volumio it just worked and was by far the most stable of them. and it ticked the boxes of what i want (internet radio, upnp steaming and spotify connect support)

**Comment by moodeaudio** [comment]
Closed due to being stale
